(include "sensors/sensors.h")

(in-package :cl-lmsensors)

(constant (+sensors-api-version+ "SENSORS_API_VERSION"))

;(constant (+sensors-chip-name-prefix-any+ "SENSORS_CHIP_NAME_PREFIX_ANY")) this is a null pointer and only nums are supported
(constant (+sensors-chip-name-address-any+ "SENSORS_CHIP_NAME_ADDR_ANY"))

(constant (+sensors-bus-type-any+ "SENSORS_BUS_TYPE_ANY"))
(constant (+sensors-bus-type-i2c+ "SENSORS_BUS_TYPE_I2C"))
(constant (+sensors-bus-type-isa+ "SENSORS_BUS_TYPE_ISA"))
(constant (+sensors-bus-type-pci+ "SENSORS_BUS_TYPE_PCI"))
(constant (+sensors-bus-type-spi+ "SENSORS_BUS_TYPE_SPI"))
(constant (+sensors-bus-type-virtual+ "SENSORS_BUS_TYPE_VIRTUAL"))
(constant (+sensors-bus-type-acpi+ "SENSORS_BUS_TYPE_ACPI"))
(constant (+sensors-bus-type-hid+ "SENSORS_BUS_TYPE_HID"))
(constant (+sensors-bus-type-mdio+ "SENSORS_BUS_TYPE_MDIO"))

(constant (+sensors-bus-nr-any+ "SENSORS_BUS_NR_ANY"))
(constant (+sensors-bus-nr-ignore+ "SENSORS_BUS_NR_IGNORE"))

(cstruct sensors-bus-id "sensors_bus_id")
(cstruct sensors-chip-name "sensors_chip_name"
	 (bus "bus" :type (:struct sensors-bus-id)))

(ctype size-t "size_t")

(cenum sensors-feature-type
       ((:sensors-feature-in "SENSORS_FEATURE_IN"))
       ((:sensors-feature-fan "SENSORS_FEATURE_FAN"))
       ((:sensors-feature-temp "SENSORS_FEATURE_TEMP"))
       ((:sensors-feature-power "SENSORS_FEATURE_POWER"))
       ((:sensors-feature-energy "SENSORS_FEATURE_ENERGY"))
       ((:sensors-feature-curr "SENSORS_FEATURE_CURR"))
       ((:sensors-feature-humidity "SENSORS_FEATURE_HUMIDITY"))
       ((:sensors-feature-max-main "SENSORS_FEATURE_MAX_MAIN"))
       ((:sensors-feature-vid "SENSORS_FEATURE_VID"))
       ((:sensors-feature-intrusion "SENSORS_FEATURE_INTRUSION"))
       ((:sensors-feature-max-other "SENSORS_FEATURE_MAX_OTHER"))
       ((:sensors-feature-beep-enable "SENSORS_FEATURE_BEEP_ENABLE"))
       ((:sensors-feature-max "SENSORS_FEATURE_MAX"))
       ((:sensors-feature-unknown "SENSORS_FEATURE_UNKNOWN")))

(cenum sensors-subfeature-type
       ((:sensors-subfeature-in-input "SENSORS_SUBFEATURE_IN_INPUT"))
       ((:sensors-subfeature-in-min "SENSORS_SUBFEATURE_IN_MIN"))
       ((:sensors-subfeature-in-max "SENSORS_SUBFEATURE_IN_MAX"))
       ((:sensors-subfeature-in-lcrit "SENSORS_SUBFEATURE_IN_LCRIT"))
       ((:sensors-subfeature-in-crit "SENSORS_SUBFEATURE_IN_CRIT"))
       ((:sensors-subfeature-in-average "SENSORS_SUBFEATURE_IN_AVERAGE"))
       ((:sensors-subfeature-in-lowest "SENSORS_SUBFEATURE_IN_LOWEST"))
       ((:sensors-subfeature-in-highest "SENSORS_SUBFEATURE_IN_HIGHEST"))
       ((:sensors-subfeature-in-alarm "SENSORS_SUBFEATURE_IN_ALARM"))
       ((:sensors-subfeature-in-min-alarm "SENSORS_SUBFEATURE_IN_MIN_ALARM"))
       ((:sensors-subfeature-in-max-alarm "SENSORS_SUBFEATURE_IN_MAX_ALARM"))
       ((:sensors-subfeature-in-beep "SENSORS_SUBFEATURE_IN_BEEP"))
       ((:sensors-subfeature-in-lcrit-alarm "SENSORS_SUBFEATURE_IN_LCRIT_ALARM"))
       ((:sensors-subfeature-in-crit-alarm "SENSORS_SUBFEATURE_IN_CRIT_ALARM"))
       ((:sensors-subfeature-fan-input "SENSORS_SUBFEATURE_FAN_INPUT"))
       ((:sensors-subfeature-fan-min "SENSORS_SUBFEATURE_FAN_MIN"))
       ((:sensors-subfeature-fan-max "SENSORS_SUBFEATURE_FAN_MAX"))
       ((:sensors-subfeature-fan-alarm "SENSORS_SUBFEATURE_FAN_ALARM"))
       ((:sensors-subfeature-fan-fault "SENSORS_SUBFEATURE_FAN_FAULT"))
       ((:sensors-subfeature-fan-div "SENSORS_SUBFEATURE_FAN_DIV"))
       ((:sensors-subfeature-fan-beep "SENSORS_SUBFEATURE_FAN_BEEP"))
       ((:sensors-subfeature-fan-pulses "SENSORS_SUBFEATURE_FAN_PULSES"))
       ((:sensors-subfeature-fan-min-alarm "SENSORS_SUBFEATURE_FAN_MIN_ALARM"))
       ((:sensors-subfeature-fan-max-alarm "SENSORS_SUBFEATURE_FAN_MAX_ALARM"))
       ((:sensors-subfeature-temp-input "SENSORS_SUBFEATURE_TEMP_INPUT"))
       ((:sensors-subfeature-temp-max "SENSORS_SUBFEATURE_TEMP_MAX"))
       ((:sensors-subfeature-temp-max-hyst "SENSORS_SUBFEATURE_TEMP_MAX_HYST"))
       ((:sensors-subfeature-temp-min "SENSORS_SUBFEATURE_TEMP_MIN"))
       ((:sensors-subfeature-temp-crit "SENSORS_SUBFEATURE_TEMP_CRIT"))
       ((:sensors-subfeature-temp-crit-hyst "SENSORS_SUBFEATURE_TEMP_CRIT_HYST"))
       ((:sensors-subfeature-temp-lcrit "SENSORS_SUBFEATURE_TEMP_LCRIT"))
       ((:sensors-subfeature-temp-emergency "SENSORS_SUBFEATURE_TEMP_EMERGENCY"))
       ((:sensors-subfeature-temp-emergency-hyst "SENSORS_SUBFEATURE_TEMP_EMERGENCY_HYST"))
       ((:sensors-subfeature-temp-lowest "SENSORS_SUBFEATURE_TEMP_LOWEST"))
       ((:sensors-subfeature-temp-highest "SENSORS_SUBFEATURE_TEMP_HIGHEST"))
       ((:sensors-subfeature-temp-min-hyst "SENSORS_SUBFEATURE_TEMP_MIN_HYST"))
       ((:sensors-subfeature-temp-lcrit-hyst "SENSORS_SUBFEATURE_TEMP_LCRIT_HYST"))
       ((:sensors-subfeature-temp-alarm "SENSORS_SUBFEATURE_TEMP_ALARM"))
       ((:sensors-subfeature-temp-max-alarm "SENSORS_SUBFEATURE_TEMP_MAX_ALARM"))
       ((:sensors-subfeature-temp-min-alarm "SENSORS_SUBFEATURE_TEMP_MIN_ALARM"))
       ((:sensors-subfeature-temp-crit-alarm "SENSORS_SUBFEATURE_TEMP_CRIT_ALARM"))
       ((:sensors-subfeature-temp-fault "SENSORS_SUBFEATURE_TEMP_FAULT"))
       ((:sensors-subfeature-temp-type "SENSORS_SUBFEATURE_TEMP_TYPE"))
       ((:sensors-subfeature-temp-offset "SENSORS_SUBFEATURE_TEMP_OFFSET"))
       ((:sensors-subfeature-temp-beep "SENSORS_SUBFEATURE_TEMP_BEEP"))
       ((:sensors-subfeature-temp-emergency-alarm "SENSORS_SUBFEATURE_TEMP_EMERGENCY_ALARM"))
       ((:sensors-subfeature-temp-lcrit-alarm "SENSORS_SUBFEATURE_TEMP_LCRIT_ALARM"))
       ((:sensors-subfeature-power-average "SENSORS_SUBFEATURE_POWER_AVERAGE"))
       ((:sensors-subfeature-power-average-highest "SENSORS_SUBFEATURE_POWER_AVERAGE_HIGHEST"))
       ((:sensors-subfeature-power-average-lowest "SENSORS_SUBFEATURE_POWER_AVERAGE_LOWEST"))
       ((:sensors-subfeature-power-input "SENSORS_SUBFEATURE_POWER_INPUT"))
       ((:sensors-subfeature-power-input-highest "SENSORS_SUBFEATURE_POWER_INPUT_HIGHEST"))
       ((:sensors-subfeature-power-input-lowest "SENSORS_SUBFEATURE_POWER_INPUT_LOWEST"))
       ((:sensors-subfeature-power-cap "SENSORS_SUBFEATURE_POWER_CAP"))
       ((:sensors-subfeature-power-cap-hyst "SENSORS_SUBFEATURE_POWER_CAP_HYST"))
       ((:sensors-subfeature-power-max "SENSORS_SUBFEATURE_POWER_MAX"))
       ((:sensors-subfeature-power-crit "SENSORS_SUBFEATURE_POWER_CRIT"))
       ((:sensors-subfeature-power-average-interval "SENSORS_SUBFEATURE_POWER_AVERAGE_INTERVAL"))
       ((:sensors-subfeature-power-alarm "SENSORS_SUBFEATURE_POWER_ALARM"))
       ((:sensors-subfeature-power-cap-alarm "SENSORS_SUBFEATURE_POWER_CAP_ALARM"))
       ((:sensors-subfeature-power-max-alarm "SENSORS_SUBFEATURE_POWER_MAX_ALARM"))
       ((:sensors-subfeature-power-crit-alarm "SENSORS_SUBFEATURE_POWER_CRIT_ALARM"))
       ((:sensors-subfeature-energy-input "SENSORS_SUBFEATURE_ENERGY_INPUT"))
       ((:sensors-subfeature-curr-input "SENSORS_SUBFEATURE_CURR_INPUT"))
       ((:sensors-subfeature-curr-min "SENSORS_SUBFEATURE_CURR_MIN"))
       ((:sensors-subfeature-curr-max "SENSORS_SUBFEATURE_CURR_MAX"))
       ((:sensors-subfeature-curr-lcrit "SENSORS_SUBFEATURE_CURR_LCRIT"))
       ((:sensors-subfeature-curr-crit "SENSORS_SUBFEATURE_CURR_CRIT"))
       ((:sensors-subfeature-curr-average "SENSORS_SUBFEATURE_CURR_AVERAGE"))
       ((:sensors-subfeature-curr-lowest "SENSORS_SUBFEATURE_CURR_LOWEST"))
       ((:sensors-subfeature-curr-highest "SENSORS_SUBFEATURE_CURR_HIGHEST"))
       ((:sensors-subfeature-curr-alarm "SENSORS_SUBFEATURE_CURR_ALARM"))
       ((:sensors-subfeature-curr-min-alarm "SENSORS_SUBFEATURE_CURR_MIN_ALARM"))
       ((:sensors-subfeature-curr-max-alarm "SENSORS_SUBFEATURE_CURR_MAX_ALARM"))
       ((:sensors-subfeature-curr-beep "SENSORS_SUBFEATURE_CURR_BEEP"))
       ((:sensors-subfeature-curr-lcrit-alarm "SENSORS_SUBFEATURE_CURR_LCRIT_ALARM"))
       ((:sensors-subfeature-curr-crit-alarm "SENSORS_SUBFEATURE_CURR_CRIT_ALARM"))
       ((:sensors-subfeature-humidity-input "SENSORS_SUBFEATURE_HUMIDITY_INPUT"))
       ((:sensors-subfeature-vid "SENSORS_SUBFEATURE_VID"))
       ((:sensors-subfeature-intrusion-alarm "SENSORS_SUBFEATURE_INTRUSION_ALARM"))
       ((:sensors-subfeature-intrusion-beep "SENSORS_SUBFEATURE_INTRUSION_BEEP"))
       ((:sensors-subfeature-beep-enable "SENSORS_SUBFEATURE_BEEP_ENABLE"))
       ((:sensors-subfeature-unknown "SENSORS_SUBFEATURE_UNKNOWN")))

(cstruct sensors-feature "sensors_feature"
	 (name "name" :type :string)
	 (number "number" :type :int)
	 (type "type" :type sensors-feature-type))

(cstruct sensors-subfeature "sensors_subfeature"
	 (name "name" :type :string)
	 (number "number" :type :int)
	 (type "type" :type sensors-subfeature-type)
	 (mapping "mapping" :type :int)
	 (flags "flags" :type :unsigned-int))
